/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#b4c5ff",
        "secondary-fixed-dim": "#b7c8e1",
        "on-secondary-fixed-variant": "#38485d",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "outline": "var(--color-outline)",
        "secondary-fixed": "#d3e4fe",
        "surface-container": "var(--color-surface-container)",
        "primary-container": "var(--color-primary-container)",
        "on-tertiary-fixed": "#360f00",
        "on-secondary": "#ffffff",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-background": "#191b23",
        "surface-dim": "var(--color-surface-dim)",
        "surface-variant": "var(--color-surface-container)",
        "on-secondary-container": "#54647a",
        "tertiary-fixed-dim": "#ffb596",
        "background": "#faf8ff",
        "on-error": "var(--color-on-error)",
        "tertiary-container": "#bc4800",
        "inverse-surface": "#2e3039",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-primary-fixed": "#00174b",
        "primary-fixed": "#dbe1ff",
        "secondary": "#505f76",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed-variant": "#003ea8",
        "tertiary": "#943700",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        "surface": "var(--color-surface)",
        "inverse-on-surface": "#f0f0fb",
        "surface-bright": "var(--color-surface-bright)",
        "on-surface": "var(--color-on-surface)",
        "on-tertiary-container": "#ffede6",
        "on-secondary-fixed": "#0b1c30",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "error": "var(--color-error)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-tint": "#0053db",
        "outline-variant": "var(--color-outline-variant)",
        "secondary-container": "#d0e1fb",
        "error-container": "var(--color-error-container)",
        "primary": "var(--color-primary)",
        "on-tertiary-fixed-variant": "#7d2d00",
        "on-primary": "var(--color-on-primary)",
        "on-primary-container": "var(--color-on-primary-container)",
        "tertiary-fixed": "#ffdbcd"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "0.25rem",
        "container-max": "1280px",
        "base": "4px",
        "lg": "1.5rem",
        "gutter": "1rem",
        "sm": "0.5rem",
        "md": "1rem",
        "xl": "2.5rem"
      },
      fontFamily: {
        "button": ["Inter"],
        "body-sm": ["Inter"],
        "title-md": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "label-mono": ["JetBrains Mono"],
        "body-lg": ["Inter"],
        "headline-lg": ["Hanken Grotesk"]
      },
      fontSize: {
        "button": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-mono": ["13px", { "lineHeight": "16px", "fontWeight": "500" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
